DELETE FROM "Skills";

INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (1, 'A Sharp', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (2, 'A+', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (3, 'A++', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (4, 'A-0 System', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (5, 'ABAP', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (6, 'ABC', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (7, 'ABC ALGOL', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (8, 'ABLE', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (9, 'ABSET', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (10, 'ABSYS', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (11, 'ACC', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (12, 'Accent', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (13, 'ACL2', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (14, 'ACT-III', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (15, 'Action!', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (16, 'ActionScript', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (17, 'Ada', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (18, 'Adenine', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (19, 'Agda', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (20, 'Agilent VEE', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (21, 'Agora', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (22, 'AIMMS', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (23, 'Alef', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (24, 'Algebraic Logic Functional programming language', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (25, 'ALGOL 58', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (26, 'ALGOL 60', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (27, 'ALGOL 68', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (28, 'ALGOL W', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (29, 'Alice', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (30, 'Alma-0', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (31, 'AmbientTalk', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (32, 'Amiga E', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (33, 'Amiga E#PortablE', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (34, 'AMOS', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (35, 'AMPL', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (36, 'APL', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (37, 'App Inventor for Android', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (38, 'AppleScript', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (39, 'Arc', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (40, 'ARexx', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (41, 'Argus', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (42, 'AS/400 Control Language', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (43, 'AspectJ', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (44, 'Assembly language', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (45, 'Ateji PX', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (46, 'ATS', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (47, 'Autocoder', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (48, 'Autodesk 3ds Max', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (49, 'AutoHotkey', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (50, 'AutoIt', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (51, 'AutoLISP', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (52, 'Averest', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (53, 'AWK', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (54, 'Axum', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (55, 'B', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (56, 'Babbage', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (57, 'Bash', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (58, 'BASIC', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (59, 'Batch file', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (60, 'bc', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (61, 'BCPL', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (62, 'BeanShell', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (63, 'Bertrand', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (64, 'BETA', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (65, 'Bigwig', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (66, 'Bistro', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (67, 'BitC', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (68, 'BLISS', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (69, 'Blockly', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (70, 'BlooP and FlooP', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (71, 'Blue', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (72, 'Boo', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (73, 'Boomerang', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (74, 'Business Process Execution Language', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (75, 'C--', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (76, 'C', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (77, 'C Sharp', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (78, 'C Shell', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (79, 'C/AL', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (80, 'C++', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (81, 'Caché ObjectScript', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (82, 'Caml', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (83, 'Cayenne', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (84, 'CDuce', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (85, 'Cecil', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (86, 'Cel', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (87, 'Cesil', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (88, 'Ceylon', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (89, 'CFEngine', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (90, 'Cg', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (91, 'Ch', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (92, 'CHAIN', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (93, 'Chapel', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (94, 'Charity', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (95, 'Charm', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (96, 'Chef', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (97, 'CHILL', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (98, 'CHIP-8', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (99, 'chomski', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (100, 'ChucK', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (101, 'CICS', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (102, 'Cilk', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (103, 'Citrine', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (104, 'Claire', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (105, 'Clarion', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (106, 'Clean', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (107, 'Clipper', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (108, 'CLIST', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (109, 'Clojure', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (110, 'CLU', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (111, 'CMS EXEC', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (112, 'CMS-2', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (113, 'COBOL', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (114, 'Cobra', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (115, 'CODE', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (116, 'CoffeeScript', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (117, 'Cola', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (118, 'ColdC', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (119, 'ColdFusion', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (120, 'ColdFusion Markup Language', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (121, 'COMAL', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (122, 'Combined Programming Language', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (123, 'COMIT', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (124, 'Common Intermediate Language', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (125, 'Common Lisp', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (126, 'Communicating sequential processes', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (127, 'COMPASS', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (128, 'Component Pascal', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (129, 'Computer Sciences Corporation', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (130, 'Constraint Handling Rules', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (131, 'Converge', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (132, 'Cool', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (133, 'Coq', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (134, 'Coral 66', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (135, 'Core War', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (136, 'Corn', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (137, 'CorVision', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (138, 'COWSEL', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (139, 'Cryptol', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (140, 'Csound', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (141, 'CUDA', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (142, 'Curl', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (143, 'Curry', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (144, 'Cyclone', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (145, 'Cython', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (146, 'D', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (147, 'Dart', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (148, 'DataFlex', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (149, 'Datalog', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (150, 'Datapoint''s Advanced Systems Language', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (151, 'DATATRIEVE', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (152, 'dBase', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (153, 'dc', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (154, 'Deesel', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (155, 'Delphi', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (156, 'DIBOL', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (157, 'DIGITAL Command Language', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (158, 'Dink Smallwood', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (159, 'Distributed Application Specification Language', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (160, 'Dog', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (161, 'Draco', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (162, 'DRAKON', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (163, 'Dylan', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (164, 'DYNAMO', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (165, 'E', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (166, 'E Sharp', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (167, 'Ease', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (168, 'Easy Programming Language', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (169, 'Easytrieve', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (170, 'ECMAScript', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (171, 'Edinburgh IMP', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (172, 'EGL', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (173, 'Eiffel', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (174, 'ELAN', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (175, 'Elixir', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (176, 'Elm', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (177, 'Emacs Lisp', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (178, 'Emerald', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (179, 'Epigram', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (180, 'Erlang', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (181, 'es', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (182, 'Escher', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (183, 'Esterel', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (184, 'Etoys', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (185, 'Euclid', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (186, 'Euler', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (187, 'Euphoria', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (188, 'EusLisp Robot Programming Language', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (189, 'EXEC 2', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (190, 'Executable UML', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (191, 'Executive Systems Problem Oriented Language', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (192, 'F', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (193, 'F Sharp', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (194, 'Factor', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (195, 'Falcon', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (196, 'Fantom', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (197, 'FAUST', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (198, 'FFP', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (199, 'Fjölnir', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (200, 'FL', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (201, 'Flavors', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (202, 'Flex', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (203, 'FLOW-MATIC', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (204, 'FOCAL', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (205, 'FOCUS', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (206, 'FOIL', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (207, 'FORMAC', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (208, 'Formula language', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (209, 'Forth', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (210, 'Fortran', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (211, 'Fortress', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (212, 'FoxBase', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (213, 'FoxPro', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (214, 'FP', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (215, 'FPr', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (216, 'Franz Lisp', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (217, 'Frege', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (218, 'F-Script', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (219, 'G', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (220, 'Game Oriented Assembly Lisp', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (221, 'GameMaker: Studio', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (222, 'GameMonkey Script', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (223, 'GAP computer algebra system', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (224, 'G-code', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (225, 'General Algebraic Modeling System', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (226, 'Generic Java', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (227, 'Genie', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (228, 'Geometric Description Language', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (229, 'GEORGE', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (230, 'GLSL', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (231, 'GNU E', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (232, 'GNU Octave', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (233, 'Go', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (234, 'Go!', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (235, 'Gödel', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (236, 'Godiva', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (237, 'Golden master', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (238, 'Golo', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (239, 'Google Apps Script', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (240, 'Gosu', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (241, 'GPSS', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (242, 'GRASS', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (243, 'Groovy', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (244, 'Hack', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (245, 'HAL/S', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (246, 'Hamilton C shell', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (247, 'Harbour', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (248, 'Hartmann pipeline', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (249, 'Hartmann pipelines', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (250, 'Haskell', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (251, 'Haxe', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (252, 'High Level Assembly', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (253, 'High Level Shader Language', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (254, 'Hop', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (255, 'Hope', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (256, 'Hopscotch', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (257, 'Hugo', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (258, 'Hume', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (259, 'HyperTalk', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (260, 'IBM 1401 Symbolic Programming System', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (261, 'IBM 1620 GOTRAN', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (262, 'IBM Basic assembly language', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (263, 'IBM HAScript', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (264, 'IBM Informix-4GL', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (265, 'IBM RPG', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (266, 'ICI', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (267, 'Icon', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (268, 'Id', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (269, 'IDL', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (270, 'Idris', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (271, 'IMP', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (272, 'Inform', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (273, 'Information Processing Language', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (274, 'IntelliCorp', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (275, 'Io', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (276, 'Ioke', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (277, 'IPTSCRAE', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (278, 'ISLISP', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (279, 'ISPF', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (280, 'ISWIM', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (281, 'J', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (282, 'J Sharp', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (283, 'JADE', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (284, 'Jako', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (285, 'JAL', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (286, 'Janus', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (287, 'JASS', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (288, 'Java', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (289, 'JavaFX Script', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (290, 'JavaScript', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (291, 'JEAN', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (292, 'Job Control Language', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (293, 'Join Java', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (294, 'JOSS', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (295, 'Joule', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (296, 'JOVIAL', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (297, 'Joy', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (298, 'JScript', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (299, 'JScript .NET', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (300, 'Julia', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (301, 'Jython', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (302, 'K', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (303, 'Kaleidoscope', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (304, 'Karel', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (305, 'Karel++', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (306, 'Kent Recursive Calculator', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (307, 'KiXtart', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (308, 'Klerer-May System', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (309, 'Knowledge Interchange Format', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (310, 'Kojo', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (311, 'Korn shell', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (312, 'Kotlin', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (313, 'KRL', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (314, 'KRYPTON', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (315, 'L', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (316, 'L Sharp', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (317, 'LabVIEW', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (318, 'Ladder logic', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (319, 'Lagoona', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (320, 'Language for Instruction Set Architecture', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (321, 'LANSA', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (322, 'Lasso', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (323, 'LaTeX', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (324, 'Lava', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (325, 'LC-3', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (326, 'Leda', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (327, 'Lego Mindstorms', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (328, 'LilyPond', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (329, 'Limbo', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (330, 'Limnor', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (331, 'LINC 4GL', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (332, 'Linden Scripting Language', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (333, 'Lingo', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (334, 'LIS', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (335, 'Lisaac', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (336, 'Lisp', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (337, 'Lite-C', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (338, 'Lithe', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (339, 'Little b', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (340, 'Little Implementation Language', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (341, 'LiveCode', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (342, 'LiveScript', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (343, 'Logo', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (344, 'Logtalk', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (345, 'LotusScript', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (346, 'LPC', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (347, 'LSE', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (348, 'Lua', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (349, 'Lucid', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (350, 'Lustre', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (351, 'LYaPAS', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (352, 'Lynx', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (353, 'M Sharp', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (354, 'M2001', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (355, 'M4', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (356, 'Machine code', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (357, 'MAD', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (358, 'Magik', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (359, 'Magma computer algebra system', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (360, 'make', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (361, 'Maple', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (362, 'MAPPER now part of BIS', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (363, 'MARK IV', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (364, 'Mary', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (365, 'Mathematica', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (366, 'MATH-MATIC', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (367, 'MATLAB', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (368, 'Max', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (369, 'Maxima', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (370, 'Maya Embedded Language', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (371, 'MDL', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (372, 'Mercury', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (373, 'Mesa', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (374, 'Metacard', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (375, 'Metafont', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (376, 'Microassembler', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (377, 'MicroScript', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (378, 'Microsoft Dynamics AX', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (379, 'Microsoft Macro Assembler', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (380, 'Microsoft Small Basic', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (381, 'MIIS', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (382, 'MillScript', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (383, 'MIMIC', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (384, 'Mirah', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (385, 'Miranda', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (386, 'MIRC scripting language', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (387, 'MIVA Script', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (388, 'ML', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (389, 'Moby', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (390, 'Model 204', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (391, 'Modelica', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (392, 'Modula', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (393, 'Modula-2', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (394, 'Modula-3', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (395, 'Mohol programming languages', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (396, 'MOO', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (397, 'Mortran', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (398, 'Mouse', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (399, 'MPD', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (400, 'MUMPS', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (401, 'Mystic BBS', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (402, 'Napier88', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (403, 'Neko', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (404, 'Nemerle', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (405, 'nesC', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (406, 'NESL', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (407, 'Net.Data', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (408, 'NetLogo', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (409, 'NetRexx', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (410, 'Netwide Assembler', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (411, 'NewLISP', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (412, 'NEWP', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (413, 'Newspeak', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (414, 'NewtonScript', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (415, 'NGL', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (416, 'Nial', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (417, 'Nice', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (418, 'Nickle', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (419, 'Nim', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (420, 'NORD Programming Language', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (421, 'Not eXactly C', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (422, 'Not Quite C', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (423, 'Nu', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (424, 'Nullsoft Scriptable Install System', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (425, 'NWScript', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (426, 'NXT-G', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (427, 'o:XML', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (428, 'Oak', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (429, 'Oberon', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (430, 'OBJ2', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (431, 'Object Lisp', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (432, 'Object Pascal', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (433, 'Object REXX', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (434, 'Objective-C', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (435, 'Objective-J', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (436, 'ObjectLOGO', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (437, 'Obliq', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (438, 'OCaml', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (439, 'occam', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (440, 'occam-π', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (441, 'OmniMark', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (442, 'Onyx', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (443, 'Opa', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (444, 'Opal', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (445, 'Open Programming Language', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (446, 'OpenCL', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (447, 'OpenEdge Advanced Business Language', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (448, 'OPS5', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (449, 'OptimJ', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (450, 'Orc', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (451, 'ORCA/Modula-2', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (452, 'Oriel', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (453, 'Orwell', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (454, 'Oxygene', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (455, 'Oz', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (456, 'P Sharp', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (457, 'P′′', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (458, 'Parallax Propeller', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (459, 'ParaSail', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (460, 'PARI/GP', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (461, 'Pascal', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (462, 'PCASTL', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (463, 'PEARL', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (464, 'PeopleCode', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (465, 'Perl', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (466, 'Perl Data Language', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (467, 'Perl6', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (468, 'Pharo', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (469, 'PHP', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (470, 'Phrogram', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (471, 'Pico', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (472, 'Picolisp', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (473, 'Pict', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (474, 'Pike', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (475, 'PIKT', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (476, 'PILOT', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (477, 'Pizza', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (478, 'PL/0', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (479, 'PL/C', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (480, 'PL/I', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (481, 'PL/I – ISO 6160', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (482, 'PL/M', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (483, 'PL/P', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (484, 'PL/SQL', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (485, 'PL-11', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (486, 'PL360', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (487, 'PLANC', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (488, 'Plankalkül', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (489, 'Planner', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (490, 'PLEX', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (491, 'PLEXIL', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (492, 'Plus', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (493, 'Polymorphic Programming Language', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (494, 'POP-11', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (495, 'PostScript', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (496, 'PowerBuilder – 4GL GUI applcation generator from Sybase', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (497, 'Powerhouse', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (498, 'PowerShell', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (499, 'Pro*C', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (500, 'Processing', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (501, 'Processing.js', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (502, 'Programming Language for Business', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (503, 'Programming language for Computable Functions', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (504, 'Prograph', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (505, 'PROIV', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (506, 'Prolog', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (507, 'PROMAL', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (508, 'Promela', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (509, 'PROSE modeling language', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (510, 'Protel', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (511, 'ProvideX', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (512, 'Pure', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (513, 'Python', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (514, 'Q', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (515, 'Qalb', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (516, 'QtScript', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (517, 'QuakeC', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (518, 'Qualcomm Brew', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (519, 'Quantum programming', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (520, 'R', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (521, 'R++', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (522, 'Racket', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (523, 'RAPID', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (524, 'Rapira', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (525, 'Ratfiv', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (526, 'Ratfor', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (527, 'rc', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (528, 'REBOL', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (529, 'Red', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (530, 'REFAL', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (531, 'Reia', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (532, 'Revolution', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (533, 'REXX', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (534, 'Rlab', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (535, 'Robot Battle', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (536, 'ROOP', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (537, 'RPL', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (538, 'RTL/2', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (539, 'Ruby', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (540, 'RuneScape', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (541, 'Rust', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (542, 'S', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (543, 'S/SL programming language', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (544, 'S2', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (545, 'S3', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (546, 'SabreTalk', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (547, 'SA-C', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (548, 'SAIL', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (549, 'SALSA', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (550, 'SAM76', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (551, 'SAS System', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (552, 'SASL', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (553, 'Sather', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (554, 'Sawzall', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (555, 'Scala', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (556, 'Scheme', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (557, 'Scilab', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (558, 'Scratch', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (559, 'Script.NET', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (560, 'Secure Operations Language', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (561, 'Sed', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (562, 'Seed7', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (563, 'Self', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (564, 'SenseTalk', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (565, 'SequenceL', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (566, 'SETL', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (567, 'SIGNAL', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (568, 'SiMPLE', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (569, 'SIMSCRIPT', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (570, 'Simula', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (571, 'Simulink', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (572, 'SISAL', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (573, 'S-Lang', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (574, 'SLIP', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (575, 'SMALL', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (576, 'Smalltalk', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (577, 'Snap!', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (578, 'SNOBOL', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (579, 'Snowball programming language', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (580, 'SP/k', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (581, 'Span', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (582, 'SPARK', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (583, 'Speedcoding', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (584, 'S-PLUS', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (585, 'SQR', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (586, 'Squeak', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (587, 'Squirrel', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (588, 'SR', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (589, 'Stackless Python', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (590, 'Standard ML', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (591, 'Starlogo', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (592, 'Stata', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (593, 'Stateflow', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (594, 'Strand', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (595, 'Subtext', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (596, 'Superbase database', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (597, 'SuperCollider', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (598, 'SuperTalk', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (599, 'Swift', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (600, 'SYMPL', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (601, 'SyncCharts', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (602, 'SystemVerilog', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (603, 'T', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (604, 'TACL', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (605, 'TACPOL', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (606, 'TADS', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (607, 'Tcl', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (608, 'Tea', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (609, 'TELCOMP', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (610, 'Tensilica Instruction Extension', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (611, 'TeX', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (612, 'text Editor and Corrector', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (613, 'Text Executive Programming Language', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (614, 'text Processing Utility', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (615, 'Timber', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (616, 'TMG', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (617, 'Tom', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (618, 'TouchDevelop', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (619, 'TRAC', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (620, 'Transaction Application Language', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (621, 'Transact-SQL', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (622, 'TTCN', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (623, 'TTM', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (624, 'Turbo C++', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (625, 'Turing', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (626, 'TUTOR', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (627, 'TXL', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (628, 'TypeScript', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (629, 'Ubercode', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (630, 'UCSD Pascal', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (631, 'Umple', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (632, 'Unicon', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (633, 'Uniface', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (634, 'UNITY', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (635, 'Unix shell', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (636, 'UnrealScript', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (637, 'Vala', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (638, 'VBScript', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (639, 'Visual Basic', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (640, 'Visual Basic .NET', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (641, 'Visual Basic for Applications', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (642, 'Visual DataFlex', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (643, 'Visual DialogScript', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (644, 'Visual Fortran', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (645, 'Visual FoxPro', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (646, 'Visual J#', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (647, 'Visual J++', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (648, 'Visual Objects', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (649, 'Visual Prolog', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (650, 'VSXu', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (651, 'vvvv', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (652, 'WATFIV', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (653, 'WebDNA', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (654, 'WebQL', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (655, 'Whiley', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (656, 'Winbatch', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (657, 'Windows PowerShell', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (658, 'Wolfram Language', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (659, 'Wyvern', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (660, 'X Sharp', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (661, 'X10', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (662, 'XBL', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (663, 'XC Programming Language', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (664, 'xHarbour', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (665, 'XL', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (666, 'Xojo', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (667, 'XOTcl', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (668, 'XPL', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (669, 'XPL0', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (670, 'XQuery', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (671, 'XSB', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (672, 'XSL Transformations', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (673, 'Xtend', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (674, 'Yorick', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (675, 'YQL', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (676, 'YT', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (677, 'Z notation', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (678, 'Zeno', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (679, 'ZOPL', NOW(), NOW()); 
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt") VALUES (680, 'ZPL', NOW(), NOW()); 

INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (681, 'Spring', NOW(), NOW(),288);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (682, 'Struts', NOW(), NOW(),288);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (683, 'Apache Axis', NOW(), NOW(),288);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (684, 'Apache Xerces', NOW(), NOW(),288);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (685, 'Hibernate', NOW(), NOW(),288);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (686, 'JDOM', NOW(), NOW(),288);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (687, 'Java Applet', NOW(), NOW(),288);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (688, 'Apache Velocity', NOW(), NOW(),288);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (689, 'Apache ORO', NOW(), NOW(),288);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (690, 'JAX-WS', NOW(), NOW(),288);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (691, 'JPA', NOW(), NOW(),288);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (692, 'Turbine', NOW(), NOW(),288);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (693, 'Tapestry', NOW(), NOW(),288);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (694, 'WebWork', NOW(), NOW(),288);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (695, 'Cocoon', NOW(), NOW(),288);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (696, 'Maverick', NOW(), NOW(),288);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (697, 'Echo', NOW(), NOW(),288);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (698, 'SOFIA', NOW(), NOW(),288);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (699, 'Verge', NOW(), NOW(),288);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (700, 'Anvil', NOW(), NOW(),288);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (701, 'Jaffa', NOW(), NOW(),288);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (702, 'Japple', NOW(), NOW(),288);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (703, 'JPublish', NOW(), NOW(),288);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (704, 'Jucas', NOW(), NOW(),288);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (705, 'MyFaces', NOW(), NOW(),288);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (706, 'WebOnSwing', NOW(), NOW(),288);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (707, 'Chrysalis', NOW(), NOW(),288);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (708, 'VRaptor', NOW(), NOW(),288);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (709, 'Swinglets', NOW(), NOW(),288);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (710, 'Millstone', NOW(), NOW(),288);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (711, 'Wicket', NOW(), NOW(),288);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (712, 'SwingWeb', NOW(), NOW(),288);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (713, 'Macaw', NOW(), NOW(),288);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (714, 'Barracuda', NOW(), NOW(),288);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (715, 'RIFE', NOW(), NOW(),288);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (716, 'DWR', NOW(), NOW(),288);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (717, 'JSPWidget', NOW(), NOW(),288);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (718, 'JOSSO', NOW(), NOW(),288);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (719, 'JAT', NOW(), NOW(),288);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (720, 'OpenXava', NOW(), NOW(),288);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (721, 'Stripes', NOW(), NOW(),288);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (722, 'Click', NOW(), NOW(),288);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (723, 'ZK', NOW(), NOW(),288);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (724, 'Caramba', NOW(), NOW(),288);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (725, 'wingS', NOW(), NOW(),288);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (726, 'Helma', NOW(), NOW(),288);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (727, 'Restlet', NOW(), NOW(),288);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (728, 'Brill', NOW(), NOW(),288);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (729, 'ztemplates', NOW(), NOW(),288);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (730, 'Aranea Web Framework', NOW(), NOW(),288);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (731, 'RSF', NOW(), NOW(),288);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (732, 'Strecks', NOW(), NOW(),288);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (733, 'Google Web Toolkit', NOW(), NOW(),288);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (734, 'Aurora', NOW(), NOW(),288);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (735, 'ThinWire', NOW(), NOW(),288);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (736, 'Roma Meta Framework', NOW(), NOW(),288);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (737, 'Pustefix', NOW(), NOW(),288);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (738, 'jWic', NOW(), NOW(),288);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (739, 'Calyxo', NOW(), NOW(),288);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (740, 'Mentawai', NOW(), NOW(),288);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (741, 'Trimpath Junction', NOW(), NOW(),288);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (742, 'Makumba', NOW(), NOW(),288);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (743, 'AribaWeb', NOW(), NOW(),288);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (744, 'fleXive', NOW(), NOW(),288);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (745, 'Flower framework', NOW(), NOW(),288);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (746, 'Hamlets', NOW(), NOW(),288);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (747, 'Induction', NOW(), NOW(),288);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (748, 'JVx', NOW(), NOW(),288);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (749, 'jZeno', NOW(), NOW(),288);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (750, 'Pandora', NOW(), NOW(),288);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (751, 'Playframework', NOW(), NOW(),288);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (752, 'SerfJ', NOW(), NOW(),288);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (753, 'Sombrero', NOW(), NOW(),288);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (754, 'Vaadin', NOW(), NOW(),288);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (755, 'Vroom', NOW(), NOW(),288);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (756, 'wro4j', NOW(), NOW(),288);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (757, 'Requests', NOW(), NOW(),513);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (758, 'Scrapy', NOW(), NOW(),513);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (759, 'wxPython', NOW(), NOW(),513);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (760, 'Pillow', NOW(), NOW(),513);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (761, 'SQLAlchemy', NOW(), NOW(),513);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (762, 'BeautifulSoup', NOW(), NOW(),513);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (763, 'Twisted', NOW(), NOW(),513);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (764, 'NumPy', NOW(), NOW(),513);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (765, 'SciPy', NOW(), NOW(),513);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (766, 'matplotlib', NOW(), NOW(),513);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (767, 'Pygame', NOW(), NOW(),513);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (768, 'Pyglet', NOW(), NOW(),513);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (769, 'pyQT', NOW(), NOW(),513);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (770, 'pyGtk', NOW(), NOW(),513);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (771, 'Scapy', NOW(), NOW(),513);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (772, 'pywin32', NOW(), NOW(),513);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (773, 'nltk', NOW(), NOW(),513);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (774, 'nose', NOW(), NOW(),513);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (775, 'SymPy', NOW(), NOW(),513);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (776, 'IPython', NOW(), NOW(),513);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (777, 'Dojo Toolkit', NOW(), NOW(),290);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (778, 'jQuery', NOW(), NOW(),290);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (779, 'midori', NOW(), NOW(),290);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (780, 'MooTools', NOW(), NOW(),290);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (781, 'Prototype JavaScript Framework', NOW(), NOW(),290);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (782, 'React.js', NOW(), NOW(),290);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (783, 'YUI Library', NOW(), NOW(),290);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (784, 'BitsyCode Javascript Library', NOW(), NOW(),290);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (785, 'Ext JS of Sencha', NOW(), NOW(),290);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (786, 'AngularJS', NOW(), NOW(),290);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (787, 'Bootstrap', NOW(), NOW(),290);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (788, 'UIkit', NOW(), NOW(),290);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (789, 'SemanticUI', NOW(), NOW(),290);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (790, 'DHTMLX', NOW(), NOW(),290);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (791, 'Dojo Widgets', NOW(), NOW(),290);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (792, 'ZURB Foundation', NOW(), NOW(),290);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (793, 'Google''s Polymer paper elements', NOW(), NOW(),290);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (794, 'jQuery UI', NOW(), NOW(),290);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (795, 'jQWidgets', NOW(), NOW(),290);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (796, 'Ignite UI of Infragistics', NOW(), NOW(),290);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (797, 'Kendo UI of Telerik', NOW(), NOW(),290);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (798, 'OpenUI5 of SAP', NOW(), NOW(),290);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (799, 'qooxdoo', NOW(), NOW(),290);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (800, 'SmartClient', NOW(), NOW(),290);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (801, 'Syncfusion', NOW(), NOW(),290);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (802, 'Webix', NOW(), NOW(),290);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (803, 'WinJS', NOW(), NOW(),290);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (804, 'GemFox: Jquery Add-on', NOW(), NOW(),290);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (805, 'Ample SDK', NOW(), NOW(),290);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (806, 'Glow', NOW(), NOW(),290);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (807, 'Lively Kernel', NOW(), NOW(),290);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (808, 'Script.aculo.us', NOW(), NOW(),290);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (809, 'Google Closure Library', NOW(), NOW(),290);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (810, 'Joose', NOW(), NOW(),290);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (811, 'JsPHP', NOW(), NOW(),290);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (812, 'Microsoft''s Ajax library', NOW(), NOW(),290);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (813, 'MochiKit', NOW(), NOW(),290);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (814, 'PDF.js', NOW(), NOW(),290);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (815, 'Rico', NOW(), NOW(),290);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (816, 'Socket.IO', NOW(), NOW(),290);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (817, 'Spry framework', NOW(), NOW(),290);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (818, 'Underscore.js', NOW(), NOW(),290);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (819, 'Bitsycode.js', NOW(), NOW(),290);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (820, 'Cascade Framework', NOW(), NOW(),290);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (821, 'Handlebars', NOW(), NOW(),290);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (822, 'jQuery Mobile', NOW(), NOW(),290);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (823, 'Mustache', NOW(), NOW(),290);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (824, 'Jasmine', NOW(), NOW(),290);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (825, 'Mocha', NOW(), NOW(),290);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (826, 'QUnit', NOW(), NOW(),290);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (827, 'Unit.js', NOW(), NOW(),290);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (828, 'Backbone.js', NOW(), NOW(),290);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (829, 'Cappuccino', NOW(), NOW(),290);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (830, 'Chaplin.js', NOW(), NOW(),290);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (831, 'Echo', NOW(), NOW(),290);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (832, 'Ember.js', NOW(), NOW(),290);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (833, 'Enyo', NOW(), NOW(),290);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (834, 'Ext JS', NOW(), NOW(),290);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (835, 'Google Web Toolkit', NOW(), NOW(),290);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (836, 'JavaScriptMVC', NOW(), NOW(),290);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (837, 'Knockout', NOW(), NOW(),290);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (838, 'Meteor', NOW(), NOW(),290);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (839, 'Mojito', NOW(), NOW(),290);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (840, 'Rialto Toolkit', NOW(), NOW(),290);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (841, 'SproutCore', NOW(), NOW(),290);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (842, 'Wakanda Framework', NOW(), NOW(),290);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (843, 'Modernizr', NOW(), NOW(),290);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (844, 'WPF', NOW(), NOW(),77);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (845, 'WCF', NOW(), NOW(),77);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (846, 'Windows Forms', NOW(), NOW(),77);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (847, 'C5 Generic Collection', NOW(), NOW(),77);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (848, 'Wintellect''s Power Collection', NOW(), NOW(),77);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (849, 'DotSpatial', NOW(), NOW(),77);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (850, 'MonoGame', NOW(), NOW(),77);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (851, 'Accord', NOW(), NOW(),77);
INSERT INTO "Skills" (id, name, "createdAt", "updatedAt", "parent_Skill_id") VALUES (852, 'LINQ', NOW(), NOW(),77);

SELECT setval('"Skills_id_seq"', (SELECT MAX(id) FROM "Skills"));