
DELETE FROM "Ratings";

INSERT INTO "Ratings" (id, rating, feedback, "createdAt", "updatedAt", "PositionId", "UserId") VALUES (1, 3, 'Ok. But you are lacking commitment.', NOW(), NOW(), 7, 1);
INSERT INTO "Ratings" (id, rating, feedback, "createdAt", "updatedAt", "PositionId", "UserId") VALUES (2, 4, 'You are such a jolly good fellow', NOW(), NOW(), 8, 1);
INSERT INTO "Ratings" (id, rating, feedback, "createdAt", "updatedAt", "PositionId", "UserId") VALUES (3, 5, 'You did perfect ;-) See you soon.', NOW(), NOW(), 9, 1);
INSERT INTO "Ratings" (id, rating, feedback, "createdAt", "updatedAt", "PositionId", "UserId") VALUES (4, 3, 'Ok. But you are lacking commitment.', NOW(), NOW(), 10, 1);
INSERT INTO "Ratings" (id, rating, feedback, "createdAt", "updatedAt", "PositionId", "UserId") VALUES (5, 5, 'You did perfect ;-) See you soon.', NOW(), NOW(), 12, 1);
INSERT INTO "Ratings" (id, rating, feedback, "createdAt", "updatedAt", "PositionId", "UserId") VALUES (6, 2, 'May we never meet again.', NOW(), NOW(), 116, 23);
INSERT INTO "Ratings" (id, rating, feedback, "createdAt", "updatedAt", "PositionId", "UserId") VALUES (7, 5, 'You did perfect ;-) See you soon.', NOW(), NOW(), 119, 23);
INSERT INTO "Ratings" (id, rating, feedback, "createdAt", "updatedAt", "PositionId", "UserId") VALUES (8, 5, 'You did perfect ;-) See you soon.', NOW(), NOW(), 134, 26);
INSERT INTO "Ratings" (id, rating, feedback, "createdAt", "updatedAt", "PositionId", "UserId") VALUES (9, 2, 'May we never meet again.', NOW(), NOW(), 135, 27);
INSERT INTO "Ratings" (id, rating, feedback, "createdAt", "updatedAt", "PositionId", "UserId") VALUES (10, 1, 'You were awful!', NOW(), NOW(), 136, 27);
INSERT INTO "Ratings" (id, rating, feedback, "createdAt", "updatedAt", "PositionId", "UserId") VALUES (11, 4, 'You are such a jolly good fellow', NOW(), NOW(), 138, 27);
INSERT INTO "Ratings" (id, rating, feedback, "createdAt", "updatedAt", "PositionId", "UserId") VALUES (12, 3, 'Ok. But you are lacking commitment.', NOW(), NOW(), 139, 27);
INSERT INTO "Ratings" (id, rating, feedback, "createdAt", "updatedAt", "PositionId", "UserId") VALUES (13, 2, 'May we never meet again.', NOW(), NOW(), 140, 27);
INSERT INTO "Ratings" (id, rating, feedback, "createdAt", "updatedAt", "PositionId", "UserId") VALUES (14, 1, 'You were awful!', NOW(), NOW(), 141, 27);
INSERT INTO "Ratings" (id, rating, feedback, "createdAt", "updatedAt", "PositionId", "UserId") VALUES (15, 1, 'You were awful!', NOW(), NOW(), 144, 27);
INSERT INTO "Ratings" (id, rating, feedback, "createdAt", "updatedAt", "PositionId", "UserId") VALUES (16, 3, 'Ok. But you are lacking commitment.', NOW(), NOW(), 145, 27);
INSERT INTO "Ratings" (id, rating, feedback, "createdAt", "updatedAt", "PositionId", "UserId") VALUES (17, 4, 'You are such a jolly good fellow', NOW(), NOW(), 155, 31);
INSERT INTO "Ratings" (id, rating, feedback, "createdAt", "updatedAt", "PositionId", "UserId") VALUES (18, 4, 'You are such a jolly good fellow', NOW(), NOW(), 156, 31);
INSERT INTO "Ratings" (id, rating, feedback, "createdAt", "updatedAt", "PositionId", "UserId") VALUES (19, 1, 'You were awful!', NOW(), NOW(), 158, 31);
INSERT INTO "Ratings" (id, rating, feedback, "createdAt", "updatedAt", "PositionId", "UserId") VALUES (20, 5, 'You did perfect ;-) See you soon.', NOW(), NOW(), 159, 31);
INSERT INTO "Ratings" (id, rating, feedback, "createdAt", "updatedAt", "PositionId", "UserId") VALUES (21, 3, 'Ok. But you are lacking commitment.', NOW(), NOW(), 160, 31);
INSERT INTO "Ratings" (id, rating, feedback, "createdAt", "updatedAt", "PositionId", "UserId") VALUES (22, 2, 'May we never meet again.', NOW(), NOW(), 161, 31);
INSERT INTO "Ratings" (id, rating, feedback, "createdAt", "updatedAt", "PositionId", "UserId") VALUES (23, 1, 'You were awful!', NOW(), NOW(), 258, 41);
INSERT INTO "Ratings" (id, rating, feedback, "createdAt", "updatedAt", "PositionId", "UserId") VALUES (24, 1, 'You were awful!', NOW(), NOW(), 259, 41);
INSERT INTO "Ratings" (id, rating, feedback, "createdAt", "updatedAt", "PositionId", "UserId") VALUES (25, 2, 'May we never meet again.', NOW(), NOW(), 261, 41);
INSERT INTO "Ratings" (id, rating, feedback, "createdAt", "updatedAt", "PositionId", "UserId") VALUES (26, 1, 'You were awful!', NOW(), NOW(), 265, 43);
INSERT INTO "Ratings" (id, rating, feedback, "createdAt", "updatedAt", "PositionId", "UserId") VALUES (27, 4, 'You are such a jolly good fellow', NOW(), NOW(), 266, 43);
INSERT INTO "Ratings" (id, rating, feedback, "createdAt", "updatedAt", "PositionId", "UserId") VALUES (28, 1, 'You were awful!', NOW(), NOW(), 267, 43);
INSERT INTO "Ratings" (id, rating, feedback, "createdAt", "updatedAt", "PositionId", "UserId") VALUES (29, 3, 'Ok. But you are lacking commitment.', NOW(), NOW(), 268, 43);
INSERT INTO "Ratings" (id, rating, feedback, "createdAt", "updatedAt", "PositionId", "UserId") VALUES (30, 2, 'May we never meet again.', NOW(), NOW(), 271, 43);
INSERT INTO "Ratings" (id, rating, feedback, "createdAt", "updatedAt", "PositionId", "UserId") VALUES (31, 3, 'Ok. But you are lacking commitment.', NOW(), NOW(), 276, 46);
INSERT INTO "Ratings" (id, rating, feedback, "createdAt", "updatedAt", "PositionId", "UserId") VALUES (32, 1, 'You were awful!', NOW(), NOW(), 371, 65);
INSERT INTO "Ratings" (id, rating, feedback, "createdAt", "updatedAt", "PositionId", "UserId") VALUES (33, 4, 'You are such a jolly good fellow', NOW(), NOW(), 372, 65);
INSERT INTO "Ratings" (id, rating, feedback, "createdAt", "updatedAt", "PositionId", "UserId") VALUES (34, 3, 'Ok. But you are lacking commitment.', NOW(), NOW(), 373, 65);
INSERT INTO "Ratings" (id, rating, feedback, "createdAt", "updatedAt", "PositionId", "UserId") VALUES (35, 4, 'You are such a jolly good fellow', NOW(), NOW(), 374, 65);
INSERT INTO "Ratings" (id, rating, feedback, "createdAt", "updatedAt", "PositionId", "UserId") VALUES (36, 2, 'May we never meet again.', NOW(), NOW(), 375, 65);
INSERT INTO "Ratings" (id, rating, feedback, "createdAt", "updatedAt", "PositionId", "UserId") VALUES (37, 1, 'You were awful!', NOW(), NOW(), 377, 65);
INSERT INTO "Ratings" (id, rating, feedback, "createdAt", "updatedAt", "PositionId", "UserId") VALUES (38, 3, 'Ok. But you are lacking commitment.', NOW(), NOW(), 378, 65);
INSERT INTO "Ratings" (id, rating, feedback, "createdAt", "updatedAt", "PositionId", "UserId") VALUES (39, 4, 'You are such a jolly good fellow', NOW(), NOW(), 431, 72);
INSERT INTO "Ratings" (id, rating, feedback, "createdAt", "updatedAt", "PositionId", "UserId") VALUES (40, 1, 'You were awful!', NOW(), NOW(), 432, 72);
INSERT INTO "Ratings" (id, rating, feedback, "createdAt", "updatedAt", "PositionId", "UserId") VALUES (41, 3, 'Ok. But you are lacking commitment.', NOW(), NOW(), 475, 78);
INSERT INTO "Ratings" (id, rating, feedback, "createdAt", "updatedAt", "PositionId", "UserId") VALUES (42, 3, 'Ok. But you are lacking commitment.', NOW(), NOW(), 476, 78);
INSERT INTO "Ratings" (id, rating, feedback, "createdAt", "updatedAt", "PositionId", "UserId") VALUES (43, 2, 'May we never meet again.', NOW(), NOW(), 478, 79);
INSERT INTO "Ratings" (id, rating, feedback, "createdAt", "updatedAt", "PositionId", "UserId") VALUES (44, 1, 'You were awful!', NOW(), NOW(), 479, 79);
INSERT INTO "Ratings" (id, rating, feedback, "createdAt", "updatedAt", "PositionId", "UserId") VALUES (45, 1, 'You were awful!', NOW(), NOW(), 480, 79);
INSERT INTO "Ratings" (id, rating, feedback, "createdAt", "updatedAt", "PositionId", "UserId") VALUES (46, 3, 'Ok. But you are lacking commitment.', NOW(), NOW(), 492, 81);
INSERT INTO "Ratings" (id, rating, feedback, "createdAt", "updatedAt", "PositionId", "UserId") VALUES (47, 4, 'You are such a jolly good fellow', NOW(), NOW(), 495, 83);
INSERT INTO "Ratings" (id, rating, feedback, "createdAt", "updatedAt", "PositionId", "UserId") VALUES (48, 4, 'You are such a jolly good fellow', NOW(), NOW(), 496, 83);
INSERT INTO "Ratings" (id, rating, feedback, "createdAt", "updatedAt", "PositionId", "UserId") VALUES (49, 3, 'Ok. But you are lacking commitment.', NOW(), NOW(), 497, 83);
INSERT INTO "Ratings" (id, rating, feedback, "createdAt", "updatedAt", "PositionId", "UserId") VALUES (50, 1, 'You were awful!', NOW(), NOW(), 499, 83);
INSERT INTO "Ratings" (id, rating, feedback, "createdAt", "updatedAt", "PositionId", "UserId") VALUES (51, 4, 'You are such a jolly good fellow', NOW(), NOW(), 501, 83);
INSERT INTO "Ratings" (id, rating, feedback, "createdAt", "updatedAt", "PositionId", "UserId") VALUES (52, 3, 'Ok. But you are lacking commitment.', NOW(), NOW(), 503, 83);
INSERT INTO "Ratings" (id, rating, feedback, "createdAt", "updatedAt", "PositionId", "UserId") VALUES (53, 1, 'You were awful!', NOW(), NOW(), 504, 83);
INSERT INTO "Ratings" (id, rating, feedback, "createdAt", "updatedAt", "PositionId", "UserId") VALUES (54, 2, 'May we never meet again.', NOW(), NOW(), 505, 83);
INSERT INTO "Ratings" (id, rating, feedback, "createdAt", "updatedAt", "PositionId", "UserId") VALUES (55, 2, 'May we never meet again.', NOW(), NOW(), 528, 91);
INSERT INTO "Ratings" (id, rating, feedback, "createdAt", "updatedAt", "PositionId", "UserId") VALUES (56, 3, 'Ok. But you are lacking commitment.', NOW(), NOW(), 529, 91);
INSERT INTO "Ratings" (id, rating, feedback, "createdAt", "updatedAt", "PositionId", "UserId") VALUES (57, 4, 'You are such a jolly good fellow', NOW(), NOW(), 530, 91);
INSERT INTO "Ratings" (id, rating, feedback, "createdAt", "updatedAt", "PositionId", "UserId") VALUES (58, 5, 'You did perfect ;-) See you soon.', NOW(), NOW(), 531, 91);
INSERT INTO "Ratings" (id, rating, feedback, "createdAt", "updatedAt", "PositionId", "UserId") VALUES (59, 2, 'May we never meet again.', NOW(), NOW(), 566, 100);
INSERT INTO "Ratings" (id, rating, feedback, "createdAt", "updatedAt", "PositionId", "UserId") VALUES (60, 1, 'You were awful!', NOW(), NOW(), 568, 100);
INSERT INTO "Ratings" (id, rating, feedback, "createdAt", "updatedAt", "PositionId", "UserId") VALUES (61, 4, 'You are such a jolly good fellow', NOW(), NOW(), 578, 102);
INSERT INTO "Ratings" (id, rating, feedback, "createdAt", "updatedAt", "PositionId", "UserId") VALUES (62, 4, 'You are such a jolly good fellow', NOW(), NOW(), 724, 137);
INSERT INTO "Ratings" (id, rating, feedback, "createdAt", "updatedAt", "PositionId", "UserId") VALUES (63, 3, 'Ok. But you are lacking commitment.', NOW(), NOW(), 725, 137);
INSERT INTO "Ratings" (id, rating, feedback, "createdAt", "updatedAt", "PositionId", "UserId") VALUES (64, 3, 'Ok. But you are lacking commitment.', NOW(), NOW(), 726, 137);
INSERT INTO "Ratings" (id, rating, feedback, "createdAt", "updatedAt", "PositionId", "UserId") VALUES (65, 3, 'Ok. But you are lacking commitment.', NOW(), NOW(), 727, 137);
INSERT INTO "Ratings" (id, rating, feedback, "createdAt", "updatedAt", "PositionId", "UserId") VALUES (66, 2, 'May we never meet again.', NOW(), NOW(), 766, 143);
INSERT INTO "Ratings" (id, rating, feedback, "createdAt", "updatedAt", "PositionId", "UserId") VALUES (67, 2, 'May we never meet again.', NOW(), NOW(), 767, 143);
INSERT INTO "Ratings" (id, rating, feedback, "createdAt", "updatedAt", "PositionId", "UserId") VALUES (68, 1, 'You were awful!', NOW(), NOW(), 768, 143);
INSERT INTO "Ratings" (id, rating, feedback, "createdAt", "updatedAt", "PositionId", "UserId") VALUES (69, 4, 'You are such a jolly good fellow', NOW(), NOW(), 780, 146);
INSERT INTO "Ratings" (id, rating, feedback, "createdAt", "updatedAt", "PositionId", "UserId") VALUES (70, 5, 'You did perfect ;-) See you soon.', NOW(), NOW(), 781, 146);
INSERT INTO "Ratings" (id, rating, feedback, "createdAt", "updatedAt", "PositionId", "UserId") VALUES (71, 3, 'Ok. But you are lacking commitment.', NOW(), NOW(), 782, 146);
INSERT INTO "Ratings" (id, rating, feedback, "createdAt", "updatedAt", "PositionId", "UserId") VALUES (72, 2, 'May we never meet again.', NOW(), NOW(), 805, 149);
INSERT INTO "Ratings" (id, rating, feedback, "createdAt", "updatedAt", "PositionId", "UserId") VALUES (73, 2, 'May we never meet again.', NOW(), NOW(), 814, 151);
INSERT INTO "Ratings" (id, rating, feedback, "createdAt", "updatedAt", "PositionId", "UserId") VALUES (74, 1, 'You were awful!', NOW(), NOW(), 815, 151);
INSERT INTO "Ratings" (id, rating, feedback, "createdAt", "updatedAt", "PositionId", "UserId") VALUES (75, 1, 'You were awful!', NOW(), NOW(), 816, 151);
INSERT INTO "Ratings" (id, rating, feedback, "createdAt", "updatedAt", "PositionId", "UserId") VALUES (76, 3, 'Ok. But you are lacking commitment.', NOW(), NOW(), 826, 154);
INSERT INTO "Ratings" (id, rating, feedback, "createdAt", "updatedAt", "PositionId", "UserId") VALUES (77, 4, 'You are such a jolly good fellow', NOW(), NOW(), 827, 154);
INSERT INTO "Ratings" (id, rating, feedback, "createdAt", "updatedAt", "PositionId", "UserId") VALUES (78, 2, 'May we never meet again.', NOW(), NOW(), 828, 154);
INSERT INTO "Ratings" (id, rating, feedback, "createdAt", "updatedAt", "PositionId", "UserId") VALUES (79, 4, 'You are such a jolly good fellow', NOW(), NOW(), 829, 154);
INSERT INTO "Ratings" (id, rating, feedback, "createdAt", "updatedAt", "PositionId", "UserId") VALUES (80, 5, 'You did perfect ;-) See you soon.', NOW(), NOW(), 848, 159);
INSERT INTO "Ratings" (id, rating, feedback, "createdAt", "updatedAt", "PositionId", "UserId") VALUES (81, 2, 'May we never meet again.', NOW(), NOW(), 849, 159);
INSERT INTO "Ratings" (id, rating, feedback, "createdAt", "updatedAt", "PositionId", "UserId") VALUES (82, 3, 'Ok. But you are lacking commitment.', NOW(), NOW(), 850, 159);
INSERT INTO "Ratings" (id, rating, feedback, "createdAt", "updatedAt", "PositionId", "UserId") VALUES (83, 1, 'You were awful!', NOW(), NOW(), 853, 159);
INSERT INTO "Ratings" (id, rating, feedback, "createdAt", "updatedAt", "PositionId", "UserId") VALUES (84, 2, 'May we never meet again.', NOW(), NOW(), 877, 165);
INSERT INTO "Ratings" (id, rating, feedback, "createdAt", "updatedAt", "PositionId", "UserId") VALUES (85, 5, 'You did perfect ;-) See you soon.', NOW(), NOW(), 878, 165);
INSERT INTO "Ratings" (id, rating, feedback, "createdAt", "updatedAt", "PositionId", "UserId") VALUES (86, 1, 'You were awful!', NOW(), NOW(), 881, 165);
INSERT INTO "Ratings" (id, rating, feedback, "createdAt", "updatedAt", "PositionId", "UserId") VALUES (87, 1, 'You were awful!', NOW(), NOW(), 884, 167);
INSERT INTO "Ratings" (id, rating, feedback, "createdAt", "updatedAt", "PositionId", "UserId") VALUES (88, 1, 'You were awful!', NOW(), NOW(), 885, 167);
INSERT INTO "Ratings" (id, rating, feedback, "createdAt", "updatedAt", "PositionId", "UserId") VALUES (89, 4, 'You are such a jolly good fellow', NOW(), NOW(), 888, 167);
INSERT INTO "Ratings" (id, rating, feedback, "createdAt", "updatedAt", "PositionId", "UserId") VALUES (90, 3, 'Ok. But you are lacking commitment.', NOW(), NOW(), 889, 167);
INSERT INTO "Ratings" (id, rating, feedback, "createdAt", "updatedAt", "PositionId", "UserId") VALUES (91, 1, 'You were awful!', NOW(), NOW(), 946, 175);
INSERT INTO "Ratings" (id, rating, feedback, "createdAt", "updatedAt", "PositionId", "UserId") VALUES (92, 2, 'May we never meet again.', NOW(), NOW(), 971, 181);
INSERT INTO "Ratings" (id, rating, feedback, "createdAt", "updatedAt", "PositionId", "UserId") VALUES (93, 5, 'You did perfect ;-) See you soon.', NOW(), NOW(), 972, 181);
INSERT INTO "Ratings" (id, rating, feedback, "createdAt", "updatedAt", "PositionId", "UserId") VALUES (94, 3, 'Ok. But you are lacking commitment.', NOW(), NOW(), 973, 181);
INSERT INTO "Ratings" (id, rating, feedback, "createdAt", "updatedAt", "PositionId", "UserId") VALUES (95, 2, 'May we never meet again.', NOW(), NOW(), 1047, 198);
INSERT INTO "Ratings" (id, rating, feedback, "createdAt", "updatedAt", "PositionId", "UserId") VALUES (96, 4, 'You are such a jolly good fellow', NOW(), NOW(), 1048, 198);
INSERT INTO "Ratings" (id, rating, feedback, "createdAt", "updatedAt", "PositionId", "UserId") VALUES (97, 4, 'You are such a jolly good fellow', NOW(), NOW(), 1067, 201);
INSERT INTO "Ratings" (id, rating, feedback, "createdAt", "updatedAt", "PositionId", "UserId") VALUES (98, 1, 'You were awful!', NOW(), NOW(), 1068, 201);
INSERT INTO "Ratings" (id, rating, feedback, "createdAt", "updatedAt", "PositionId", "UserId") VALUES (99, 5, 'You did perfect ;-) See you soon.', NOW(), NOW(), 1069, 201);
INSERT INTO "Ratings" (id, rating, feedback, "createdAt", "updatedAt", "PositionId", "UserId") VALUES (100, 4, 'You are such a jolly good fellow', NOW(), NOW(), 1071, 202);
INSERT INTO "Ratings" (id, rating, feedback, "createdAt", "updatedAt", "PositionId", "UserId") VALUES (101, 1, 'You were awful!', NOW(), NOW(), 1072, 204);
INSERT INTO "Ratings" (id, rating, feedback, "createdAt", "updatedAt", "PositionId", "UserId") VALUES (102, 4, 'You are such a jolly good fellow', NOW(), NOW(), 1073, 204);
INSERT INTO "Ratings" (id, rating, feedback, "createdAt", "updatedAt", "PositionId", "UserId") VALUES (103, 5, 'You did perfect ;-) See you soon.', NOW(), NOW(), 1170, 223);
INSERT INTO "Ratings" (id, rating, feedback, "createdAt", "updatedAt", "PositionId", "UserId") VALUES (104, 3, 'Ok. But you are lacking commitment.', NOW(), NOW(), 1173, 223);
INSERT INTO "Ratings" (id, rating, feedback, "createdAt", "updatedAt", "PositionId", "UserId") VALUES (105, 5, 'You did perfect ;-) See you soon.', NOW(), NOW(), 1174, 223);
INSERT INTO "Ratings" (id, rating, feedback, "createdAt", "updatedAt", "PositionId", "UserId") VALUES (106, 1, 'You were awful!', NOW(), NOW(), 1175, 223);
INSERT INTO "Ratings" (id, rating, feedback, "createdAt", "updatedAt", "PositionId", "UserId") VALUES (107, 4, 'You are such a jolly good fellow', NOW(), NOW(), 1178, 223);
INSERT INTO "Ratings" (id, rating, feedback, "createdAt", "updatedAt", "PositionId", "UserId") VALUES (108, 4, 'You are such a jolly good fellow', NOW(), NOW(), 1186, 226);
INSERT INTO "Ratings" (id, rating, feedback, "createdAt", "updatedAt", "PositionId", "UserId") VALUES (109, 1, 'You were awful!', NOW(), NOW(), 1188, 226);
INSERT INTO "Ratings" (id, rating, feedback, "createdAt", "updatedAt", "PositionId", "UserId") VALUES (110, 2, 'May we never meet again.', NOW(), NOW(), 1189, 226);
INSERT INTO "Ratings" (id, rating, feedback, "createdAt", "updatedAt", "PositionId", "UserId") VALUES (111, 5, 'You did perfect ;-) See you soon.', NOW(), NOW(), 1190, 226);
INSERT INTO "Ratings" (id, rating, feedback, "createdAt", "updatedAt", "PositionId", "UserId") VALUES (112, 1, 'You were awful!', NOW(), NOW(), 1191, 226);
INSERT INTO "Ratings" (id, rating, feedback, "createdAt", "updatedAt", "PositionId", "UserId") VALUES (113, 1, 'You were awful!', NOW(), NOW(), 1257, 234);
INSERT INTO "Ratings" (id, rating, feedback, "createdAt", "updatedAt", "PositionId", "UserId") VALUES (114, 4, 'You are such a jolly good fellow', NOW(), NOW(), 1258, 234);
INSERT INTO "Ratings" (id, rating, feedback, "createdAt", "updatedAt", "PositionId", "UserId") VALUES (115, 2, 'May we never meet again.', NOW(), NOW(), 1259, 234);

SELECT setval('"Ratings_id_seq"', (SELECT MAX(id) FROM "Ratings"));